name: Mac Release

on: [push]

jobs:
  mac_release:
    name: "Release Version ${{ github.event.inputs.version }}"
    runs-on: "macos-13"
    strategy:
      matrix:
        arch: ["x86_64", "arm64"]
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set Up Code Signing 🔑
        uses: ./.github/actions/setup-macos-codesigning
        id: codesign
        with:
          codesignIdentity: ${{ secrets.APPLE_TEAM_ID }}
          codesignCertificate: ${{ secrets.APPLE_DEVELOPER_ID_P12 }}
          certificatePassword: ${{ secrets.APPLE_DEVELOPER_ID_P12_PASSWORD }}
          keychainPassword: ${{ secrets.APPLE_DEVELOPER_KEYCHAIN_PASSWORD }}
          provisioningProfile: ${{ secrets.APPLE_DEVELOPER_PROVISIONING_PROFILE }}
      - name: "Release"
        run: |
          ./build.sh
        env:
          SLOBS_RELEASE_VERSION: ${{ github.event.inputs.version }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CI: true
          ARCH: ${{ matrix.arch }}
