name: Mac Release

on: [push]

jobs:
  mac_release:
    name: "Release Version ${{ github.event.inputs.version }}"
    runs-on: "macos-13"
    strategy:
      matrix:
        arch: ["x86_64", "arm64"]
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_ID_P12 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_ID_P12_PASSWORD }}
      - name: Set up provisioning profile for xcode
        env:
          PROVISIONING_PROFILE: ${{ secrets.APPLE_DEVELOPER_PROVISIONING_PROFILE }}
        run: |
          mkdir -p "~/Library/Developer/Xcode/UserData/Provisioning\ Profiles"
          echo "$PROVISIONING_PROFILE" | base64 --decode > "~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/Profile.provisionprofile"
      - name: "Release"
        run: |
          echo "Build the project"
          ./build.sh
        env:
          SLOBS_RELEASE_VERSION: ${{ github.event.inputs.version }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CI: true
          ARCH: ${{ matrix.arch }}
